name: Metrics
on:
  schedule: [{cron: "0 */2 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: UnoxyRich
          filename: github-metrics.svg
          template: classic
          base: header, community, repositories, metadata
          config_timezone: Asia/Shanghai

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes

          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 24

          plugin_stars: yes
          plugin_stars_limit: 3

          plugin_steam: no
          plugin_notable: yes

      - name: Generate Steam metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: UnoxyRich
          filename: steam-metrics.svg
          template: classic
          base: ""
          config_timezone: Asia/Shanghai

          plugin_isocalendar: no
          plugin_languages: no
          plugin_people: no
          plugin_stars: no
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: ${{ secrets.STEAM_USER_ID }}
          plugin_steam_sections: recently-played
          plugin_steam_games_limit: 8
          plugin_steam_recent_games_limit: 6
          plugin_steam_playtime_threshold: 0

          plugin_notable: no
